facebook: "https://facebook.com/atishay811"
twitter: "https://twitter.com/atishay811"
github: "https://github.com/atishay"
email: "contact@atishay.me"
linkedin: "https://linkedin.com/in/atishay"
name: "Atishay Jain"
location: San Francisco Bay Area, California
pinterest: 030335a810086406e6bc0b5f7f1bf740
phone: On request
hours: "**Mon-Fri:** 9:00AM - 6:00PM, PST"
