description: "Personal website of Atishay Jain, developer at Adobe Systems with over 8 years of experience developing a wide range of Adobe products, right from your favorite desktop apps and websites(full stack) to mobile. I have worked on a variety of platforms and technology domains. I love solving problems and believe in searching for the best way to solve a problem before diving in."
color: "#2962FF"
colorPickerEnabled: true
copyright: "&copy; 2016-{now} Atishay Jain. All rights reserved."
checksDarkMode: true
colorVariations:
  - name: violet
    color: 9400D3
  - name: indigo
    color: 1d48e1
  - name: blue
    color: 00D3F9
  - name: green
    color: 50d617
  - name: yellow
    color: edc166
  - name: orange
    color: ee6d45
  - name: red
    color: c92744
github: "https://github.com/atishay/atishay.github.io"
Guitar: https://guitar2svg.herokuapp.com/
Tex: https://tex2svg.herokuapp.com/
footer:
    - title: About
      content: Personal Website of Atishay Jain, Computer Scientist at Adobe Systems. I am a developer living in the San Francisco Bay area and love solving problems via technology, design, writing, talking or any other means possible.
      newsletter: Join the newsletter
    - title: Disclaimer
      content: The content of this website is mine and mine alone. It is not affiliated with any of my present or past employers, institutes or acquaintances. If you find anything offensive or any copyright infringements, please report them to me. I apologize in advance for any such errors. For more details please refer to the [Privacy Policy](/privacy) and [Terms of Use](/terms).
    - title: Recent Blog Posts
      recents: blog
      recentCount: 7
    - title: Contact Us
      contact: true
sharedHeader:
  - blog
sidebar:
  - title: license
    content: The contents of this post are available under Creative Commons Shared Alike license. You are free to use them commercially given that you provide the right attribution. Please maintain judgement as to usage - ripping off the whole website or post is not a great idea. You can read more about the license at the [Creative Commons website](http://creativecommons.org/licenses/by-sa/4.0/). <br> ![Creative Commons Shared Alike License](/image/ccbysa.png)
comment:
    sheet: 1gzXCakB9twLVlni9yuSZtQBNyp1ae_q_F1eqmPYekVc
    form: 1FAIpQLSdjkSleb2kSkQGWebNU7ZTPT7osqjj0EPc0g6Zl4Qud--jAaw
    email: emailAddress
    name: entry.1199094986
    post: entry.524983228
    comment: entry.8861571
newsletter:
  action: https://atishay.us20.list-manage.com/subscribe/post?u=5a8e4f4c993f2eae750b5922e&amp;id=72ec4151d0
  email: EMAIL
  honeypot: b_5a8e4f4c993f2eae750b5922e_72ec4151d0
