language: node_js

git:
  depth: false

branches:
  only:
  - develop

before_install:
  - sudo apt-get install -y python-pygments

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.52/hugo_0.52_Linux-64bit.deb -O /tmp/hugo.deb && sudo dpkg -i /tmp/hugo.deb
  # Clean and don't fail
  - rm -rf public || exit 0

script:
  - hugo --minify

# Deploy to github pages.
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: public
  github-token: $GITHUB_TOKEN
  on:
    branch: develop
  target-branch: master

after_deploy: "curl -X POST \"https://api.cloudflare.com/client/v4/zones/$CF_ZONE/purge_cache\" -H \"X-Auth-Email: contact@atishay.me\" \ -H \"X-Auth-Key: $CF_AUTH\" \ -H \"Content-Type: application/json\" --data '{\"purge_everything\":true}'"
