# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Atishay Jain
email: contact@atishay.me
description: > # this means to ignore newlines until "baseurl:"
  Personal website of Atishay Jain, developer at Adobe Systems with over 7 years of experience developing a wide range of
  Adobe products, right from your favorite desktop apps and websites(full stack) to mobile. I have worked on a variety of platforms
  and technology domains. I love solving problems and believe in searching for the best way to solve a problem before diving in.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://atishay.me" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: atishay811
github_username:  atishay
domain: atishay.info
twitter:
  username: atishay811
logo: /assets/img/logo.svg
defaults:
    layout: post
permalink: /blog/:year/:month/:day/:title
paginate: 9
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
theme: minima
color: lightblue # can be coffee, green. greensea, lightblue, mblue, orange, red, wisteria
plugins:
    - jekyll-mentions
    - jemoji
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-coffeescript
    - jekyll-paginate
    - jekyll-seo-tag
feed:
  path: atom.xml
exclude:
  - Gemfile
  - Gemfile.lock
sass:
    style: compressed
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
    noscript: false
kramdown:
    math_engine: mathjax
exclude: [README.md, TODO.md, CODE_OF_CONDUCT.md, TODO.md, package.json, package-lock.json]
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local, development]
  blanklines: false
  profile: false
  startings: [html, head, body]
