baseURL: "https://atishay.me"
disablePathToLower: true
languageCode: "en-us"
title: "Atishay Jain"
theme: "jain"
# Does not set the sitemap yet.
# enableRobotsTXT: true
ignoreFiles: [ ".github/", "old/", ".gitignore", "LICENSE", "README.md" ]

params:
    author: "Atishay Jain<contact@atishay.me>"
    description: "Personal website of Atishay Jain, developer at Adobe Systems with over 8 years of experience developing a wide range of Adobe products, right from your favorite desktop apps and websites(full stack) to mobile. I have worked on a variety of platforms and technology domains. I love solving problems and believe in searching for the best way to solve a problem before diving in."
    color: "#00D3F9"

author:
    facebook: "atishay811"
    twitter: "atishay811"
    github: "atishay"
    email: "contact@atishay.me"
    linkedin: "atishay"

permalinks:
  post: "/blog/:year/:month/:day/:title"

sitemap:
    changefreq: "monthly"
    priority: 0.5
    filename: "sitemap.xml"

# https://github.com/tannerlinsley/valleydesignbuild/blob/master/src/data/_authors/joe.toml
