baseURL: "https://atishay.me"
disablePathToLower: true
languageCode: "en-us"
title: "Atishay Jain"
theme: "jain"
canonifyURLs: true
# Does not set the sitemap yet.
# enableRobotsTXT: true
ignoreFiles:
    - ".github/"
    - ".gitignore"
    - "LICENSE.md"
    - "README.md"

params:
    author: "Atishay Jain<contact@atishay.me>"
    description: "Personal website of Atishay Jain, developer at Adobe Systems with over 8 years of experience developing a wide range of Adobe products, right from your favorite desktop apps and websites(full stack) to mobile. I have worked on a variety of platforms and technology domains. I love solving problems and believe in searching for the best way to solve a problem before diving in."
    color: "#00D3F9"
    github: "https://github.com/atishay/atishay.github.io"
    CSP: true

author:
    facebook: "atishay811"
    twitter: "atishay811"
    github: "atishay"
    email: "contact@atishay.me"
    linkedin: "atishay"
    name: "Atishay Jain"

permalinks:
  blog: "/blog/:year/:month/:day/:slug"

sitemap:
    changefreq: "monthly"
    priority: 0.5
    filename: "sitemap.xml"
