baseURL: "https://atishay.me"
disablePathToLower: true
languageCode: "en-us"
title: "Atishay Jain"
theme: "jain"
canonifyURLs: true
disablePathToLower: false
minify: true
# Does not set the sitemap yet.
# enableRobotsTXT: true
ignoreFiles:
    - ".github/"
    - ".gitignore"
    - "LICENSE.md"
    - "README.md"

params:
    description: "Personal website of Atishay Jain, developer at Adobe Systems with over 8 years of experience developing a wide range of Adobe products, right from your favorite desktop apps and websites(full stack) to mobile. I have worked on a variety of platforms and technology domains. I love solving problems and believe in searching for the best way to solve a problem before diving in."
    color: "#00D3F9"
    github: "https://github.com/atishay/atishay.github.io"
    CSP: true
    _topSubmenu: false
    footer:
        - title: About
          content: Personal Website of Atishay Jain, Computer Scientist at Adobe Systems. I am a developer living in the San Francisco Bay area and love solving problems via technology, design, writing, talking or any other means possible.
        - title: Disclaimer
          content: The content of this website is mine and mine alone. It is not affiliated with any of my present or past employers, institutes or acquaintances. If you find anything offensive or any copyright infringements, please report them to me. I apologize in advance for any such errors. For more details please refer to the [Privacy Policy](/privacy) and [Terms of Use](/terms).
        - title: Recent Blog Posts
          recents: blog
          recentCount: 7
        - title: Contact Us
          contact: true
    sidebar:
      - title: license
        content: The contents of this post are available under Creative Commons Shared Alike license. You are free to use them commercially given that you provide the right attribution. You can read more about the license at the [Creative Commons website](http://creativecommons.org/licenses/by-sa/4.0/). <br> ![Creative Commons Shared Alike License](/image/ccbysa.png)
    comment:
        sheet: 1gzXCakB9twLVlni9yuSZtQBNyp1ae_q_F1eqmPYekVc
        form: 1FAIpQLSdjkSleb2kSkQGWebNU7ZTPT7osqjj0EPc0g6Zl4Qud--jAaw
        email: emailAddress
        name: entry.1199094986
        post: entry.524983228
        comment: entry.8861571

cacheDir: cache
enableEmoji: true
related:
  threshold: 0
  includeNewer: true
  toLower: true
  indices:
  - name: category
    weight: 100
  - name: tags
    weight: 50
  - name: date
    weight: 10
author:
    facebook: "https://facebook.com/atishay811"
    twitter: "https://twitter.com/atishay811"
    github: "https://github.com/atishay"
    email: "contact@atishay.me"
    linkedin: "https://linkedin.com/in/atishay"
    name: "Atishay Jain"

permalinks:
  blog: "/blog/:year/:month/:day/:slug"

sitemap:
    changefreq: "monthly"
    priority: 0.5
    filename: "sitemap.xml"
