baseURL: "https://atishay.me"
disablePathToLower: true
languageCode: "en-us"
title: "Atishay Jain"
theme: "jain"
canonifyURLs: true
disablePathToLower: false
minify: true
# Does not set the sitemap yet.
# enableRobotsTXT: true
ignoreFiles:
    - ".github/"
    - ".gitignore"
    - "LICENSE.md"
    - "README.md"

params:
    description: "Personal website of Atishay Jain, developer at Adobe Systems with over 8 years of experience developing a wide range of Adobe products, right from your favorite desktop apps and websites(full stack) to mobile. I have worked on a variety of platforms and technology domains. I love solving problems and believe in searching for the best way to solve a problem before diving in."
    color: "#00D3F9"
    github: "https://github.com/atishay/atishay.github.io"
    CSP: true
    _topSubmenu: false
    footer:
        - title: About
          description: Personal Website of Atishay Jain, Computer Scientist at Adobe Systems. I am a developer living in the San Francisco Bay area and love solving problems via technology, design, writing, talking or any other means possible.
        - title: Disclaimer
          description: The content of this website is mine and mine alone. It is not affiliated with any of my present or past employers, institutes or acquaintances. If you find anything offensive or any copyright infringements, please report them to me. I apologize in advance for any such errors. For more details please refer to the [Privacy Policy](/privacy) and [Terms of Use](/terms).
        - title: Recent Blog Posts
          recents: blog
          recentCount: 7
        - title: Contact Us
          contact: true


author:
    facebook: "https://facebook.com/atishay811"
    twitter: "https://twitter.com/atishay811"
    github: "https://github.com/atishay"
    email: "contact@atishay.me"
    linkedin: "https://linkedin.com/in/atishay"
    name: "Atishay Jain"

permalinks:
  blog: "/blog/:year/:month/:day/:slug"

sitemap:
    changefreq: "monthly"
    priority: 0.5
    filename: "sitemap.xml"
