[build]
  command = "hugo --minify --baseURL $URL"
  [build.environment]
  HUGO_VERSION="0.151.0"
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: www.gravatar.com; connect-src 'self'; worker-src 'self'; frame-src www.youtube-nocookie.com; object-src 'none'"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = '''
    max-age=2592000,
    public
    '''
    Strict-Transport-Security = "max-age=2592000"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Feature-Policy = "microphone 'none'; geolocation 'none'; ambient-light-sensor 'none'; accelerometer 'none'; camera 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; midi 'none'; payment 'none'; usb 'none'; vr 'none'"
    Access-Control-Allow-Origin = "null"

[[headers]]
  for = '/*.(jpg|png|svg|mov|webp|avif)'
  [headers.values]
    Cache-Control = '''
	max-age=31536000,
	public'''

[build.processing]
  skip_processing = false
[build.processing.js]
  minify = true
[functions]
  directory = "api"
